### PR TITLE
feat: added navigation

### PR DESCRIPTION
**Pull request by AmishMishra11**
features added
- added navigation
- folder structure

- basic routing for
     - home page 
     - product page
     - wishlist
     - cart

### CODE REVIEW

**Review by prathmeshjagtap — APPROVED** [review]
Liked how you have kept the folder structure and Routes
You can also add Login Signup Routes as Well if you want

**Review by ishapatell1 — COMMENTED** [review]
Amish, your work looks quite good, please avoid unnecessary comments. I am sure you will remove these comments while refactoring your code after implementing functionalities.

**Review by ishapatell1 — APPROVED** [review]

**Review by Kavita539 — APPROVED** [review]
- Looks pretty organized and structured.
- Code is well put together and readable
- As you have put router for others, you could also do that for authentication pages too, that could be done later.

**Comment by AmishMishra11** [comment]
> Liked how you have kept the folder structure and Routes You can also add Login Signup Routes as Well if you want

I will add those after the authentication class

**Comment by AmishMishra11** [comment]
> Amish, your work looks quite good, please avoid unnecessary comments. I am sure you will remove these comments while refactoring your code after implementing functionalities.

Yes, those are just so I remember what other components to add later on that page I will remove them later.

**Pull request merged**
